version: "3.9"
services:

  db:
    image: mysql:5
    container_name: db
    environment:
      - MYSQL_DATABASE=zapata
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - ./zapata/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./zapata/db/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    restart: always

  app:
    image: app:1
    container_name: app
    build: ./zapata/app
    ports:
      - 5000:5000
    volumes:
      - ./modules:/app/modules
      - ./zapata/vault:/vault
    restart: always

volumes:
  dbdata:
