version: "3.9"

services:
  certbot:
    image: certbot:1
    container_name: certbot
    build:
      context: ./zapata/certbot
      dockerfile: Dockerfile
    volumes:
      - certs:/etc/letsencrypt
      - www:/var/www/certbot

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=zapata
      - POSTGRES_USER=zapata
      - POSTGRES_PASSWORD=zapata
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/zapata/db/dump.sql:/tmp/dump.sql
    restart: always

  app:
    image: app:1
    container_name: app
    build: ./zapata/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  reminders:
    image: reminders:1
    container_name: reminders
    build: ./zapata/reminders
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    restart: on-failure
    depends_on:
      - app

  nginx:
    image: nginx:1
    container_name: nginx
    build:
      context: ./zapata/nginx/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 8443:8443
    volumes:
      - certs:/etc/letsencrypt
      - www:/var/www/certbot
    links:
      - app
      - certbot
    restart: always

volumes:
  certs:
    name: certs
  www:
    name: www
