version: "3.9"
services:

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=zapata
      - POSTGRES_USER=zapata
      - POSTGRES_PASSWORD=zapata
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/zapata/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  app:
    image: app:1
    container_name: app
    build: ./zapata/app
    ports:
      - 5000:5000
    restart: always

volumes:
  dbdata:
