version: "3.9"
services:

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=zapata
      - POSTGRES_USER=zapata
      - POSTGRES_PASSWORD=zapata
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/zapata/db/dump.sql:/tmp/dump.sql
    restart: always

  app:
    image: app:1
    container_name: app
    build: ./zapata/app
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db

  reminders:
    image: reminders:1
    container_name: reminders
    build: ./zapata/reminders
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    restart: on-failure
    depends_on:
      - app


