version: "3.9"
services:
  vault-server:
    image: vault:1.3.2
    container_name: vault-server
    ports:
      - 8200:8200
    volumes:
      - ./zapata/vault:/vault
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  vault-client:
    image: vault:1.3.2
    container_name: vault-client
    environment:
      - VAULT_ADDR=http://vault-server:8200
    volumes:
      - ./zapata/vault/vault-init.sh:/usr/local/bin/vault-init.sh
      - ./zapata/vault/vault-init.py:/usr/local/bin/vault-init.py
      - ./zapata/vault:/vault
      - ./zapata/vault/.env:/.env
      - ./zapata/vault/requirements.txt:/requirements.txt
      - ./modules:/modules
    command: /usr/local/bin/vault-init.sh
    depends_on:
      - vault-server
    user: "0"

  db:
    image: mysql:5
    container_name: db
    environment:
      - MYSQL_DATABASE=zapata
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - ./zapata/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./zapata/db/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    restart: always

  app:
    image: app:1
    container_name: app
    build: ./zapata/app
    ports:
      - 5000:5000
    volumes:
      - ./modules:/app/modules
      - ./zapata/vault:/vault
    restart: always

volumes:
  dbdata:
