version: "3.7"
services:
  vault-server:
    image: vault:1.3.2
    container_name: vault-server
    ports:
      - 8200:8200
    volumes:
      - ./vault:/vault
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  vault-client:
    image: vault:1.3.2
    container_name: vault-client
    environment:
      - VAULT_ADDR=http://vault-server:8200
    volumes:
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - ./vault-init.py:/usr/local/bin/vault-init.py
      - ./vault:/vault
      - ./.env:/.env
      - ./requirements.lock:/requirements.lock
    command: /usr/local/bin/vault-init.sh
    depends_on:
      - vault-server
    user: "0"

  db:
    image: mysql:5
    container_name: db
    environment:
      - MYSQL_DATABASE=zapata
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./db/my.cnf:/etc/mysql/my.cnf
    depends_on:
      - vault-client
    restart: always
