name: Functional

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Spin
        run: |
          export HOME="${GITHUB_WORKSPACE}"
          docker-compose up --build -d
      - name: Test
        run: |
          export HOME="${GITHUB_WORKSPACE}"
          make functional
