name: Python application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_PASSWORD: root
      MAILCHIMP_USERNAME: no@such.email
      MAILCHIMP_APIKEY: 12345
      MAILCHIMP_LISTID: 12345

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup env file
        run: |
          ./.github/scripts/secrets2envfile.py
      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop
      - name: Build the docker-compose stack
        run: |
          cd ${GITHUB_WORKSPACE}/microservices
          docker-compose up -d
      - name: Bootstrap
        run: |
          export GUEST_HOME="${GITHUB_WORKSPACE}"
          sudo -E ./bootstrap-app.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
          pip install -r tests/requirements-test.lock
          wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
          mkdir geckodriver
          tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export GUEST_HOME="${GITHUB_WORKSPACE}"
          pytest
